-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghP7/KVOZXo3irdpJ
eGTKHGEvTSVW/nlAab2jlDJIkhCgCgYIKoZIzj0DAQehRANCAATGwPgKmCq985iW
pRc6nL99+VLR7gk5Qk7OBd+04kAuMKg6wdZ+AYTitMni9VmhqNGdX7cpDCHClVUl
Mc8AME7n
-----END PRIVATE KEY-----