// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdm7d3z2xAtukYGVKCoNOMCEt5prSx2oc',
    appId: '1:947786470894:web:917b9c58640575eb932aff',
    messagingSenderId: '947786470894',
    projectId: 'academic-student-4fe08',
    authDomain: 'academic-student-4fe08.firebaseapp.com',
    storageBucket: 'academic-student-4fe08.appspot.com',
    measurementId: 'G-9MQ7TC6G22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA760Elv6tumbZQRQXd5dCzmA3wnCiV04k',
    appId: '1:947786470894:android:5afebe615e1c8af4932aff',
    messagingSenderId: '947786470894',
    projectId: 'academic-student-4fe08',
    storageBucket: 'academic-student-4fe08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR6cINjWz8CB0NTcDWNX_CYacqPs6ykdA',
    appId: '1:947786470894:ios:c014dadee9fe6899932aff',
    messagingSenderId: '947786470894',
    projectId: 'academic-student-4fe08',
    storageBucket: 'academic-student-4fe08.appspot.com',
    iosClientId: '947786470894-f0967ihdkhccu1jet1r6m839pushs3s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.academic-student',
  );
}
